// 필사 초기 데이터 — 저작권 만료 또는 원작 문장 (public_domain / original)
export const SEED_COPYWORK = [
  {
    title: "봄",
    sourceTitle: "봄봄",
    author: "김유정",
    content: "봄이 오면 산에 들에 진달래 피고, 진달래 피면 울 엄마 보고 싶어 울었다오.",
    copyrightStatus: "public_domain",
    level: 1,
    tags: ["봄", "감성", "단문"],
  },
  {
    title: "글쓰기란",
    sourceTitle: "",
    author: "한-글",
    content: "글을 쓴다는 것은 생각을 손끝으로 꺼내는 일이다. 그 과정에서 우리는 자신이 무엇을 느끼고 무엇을 바라는지를 조금씩 알게 된다.",
    copyrightStatus: "original",
    level: 1,
    tags: ["글쓰기", "성찰"],
  },
  {
    title: "흰 수건",
    sourceTitle: "소나기",
    author: "황순원",
    content: "소년은 개울가에서 소녀를 만났다. 소녀는 물속에 발을 담그고 물장구를 치고 있었다.",
    copyrightStatus: "public_domain",
    level: 1,
    tags: ["소설", "단문", "감성"],
  },
  {
    title: "하루의 시작",
    sourceTitle: "",
    author: "한-글",
    content: "오늘 하루가 다시 시작된다. 어제와 똑같은 아침처럼 보이지만, 어제의 나와 오늘의 나는 다르다. 그 작은 차이가 쌓여 사람이 된다.",
    copyrightStatus: "original",
    level: 1,
    tags: ["일상", "성장", "아침"],
  },
  {
    title: "산",
    sourceTitle: "산문집",
    author: "법정",
    content: "아무것도 갖지 않을 때 비로소 온 세상을 갖게 된다는 것을, 무소유의 진정한 의미는 아무것도 갖지 않는 것이 아니라 불필요한 것을 갖지 않는 데 있다.",
    copyrightStatus: "public_domain",
    level: 2,
    tags: ["철학", "무소유", "성찰"],
  },
  {
    title: "나무",
    sourceTitle: "",
    author: "한-글",
    content: "나무는 제 자리에서 자란다. 바람이 불면 흔들리지만 뿌리는 움직이지 않는다. 글도 그래야 한다. 흔들려도 중심은 지키는 것.",
    copyrightStatus: "original",
    level: 1,
    tags: ["글쓰기", "비유", "단문"],
  },
  {
    title: "가을 하늘",
    sourceTitle: "메밀꽃 필 무렵",
    author: "이효석",
    content: "산허리는 온통 메밀밭이어서 피기 시작한 꽃이 소금을 뿌린 듯이 흐뭇한 달빛에 숨이 막힐 지경이었다.",
    copyrightStatus: "public_domain",
    level: 2,
    tags: ["소설", "묘사", "가을"],
  },
  {
    title: "기억",
    sourceTitle: "",
    author: "한-글",
    content: "쓰지 않으면 잊힌다. 작은 감정 하나, 스쳐 지나간 생각 하나도 글로 붙잡아두면 나중에 다시 나를 만날 수 있다.",
    copyrightStatus: "original",
    level: 1,
    tags: ["글쓰기", "기록", "단문"],
  },
  {
    title: "강",
    sourceTitle: "무진기행",
    author: "김승옥",
    content: "안개, 무진의 안개, 무진에 가득 차 있는 안개. 그것은 무진을 무진이게 하는 것이었다.",
    copyrightStatus: "public_domain",
    level: 2,
    tags: ["소설", "묘사", "분위기"],
  },
  {
    title: "천천히",
    sourceTitle: "",
    author: "한-글",
    content: "빠르게 쓰는 것보다 천천히 쓰는 것이 때로 더 많은 것을 담는다. 서두르지 않는 손끝에서 생각이 더 선명하게 흘러나온다.",
    copyrightStatus: "original",
    level: 1,
    tags: ["글쓰기", "속도", "단문"],
  },
  {
    title: "엄마의 말",
    sourceTitle: "",
    author: "한-글",
    content: "엄마가 해주시던 말이 있었다. 말이 씨가 된다고. 그래서 나는 좋은 말을 쓰려 한다. 언젠가 그 씨앗이 꽃이 되길 바라며.",
    copyrightStatus: "original",
    level: 1,
    tags: ["감성", "단문", "언어"],
  },
  {
    title: "겨울 아침",
    sourceTitle: "",
    author: "한-글",
    content: "겨울 아침의 공기는 투명하다. 숨을 내쉬면 작은 구름이 피어오른다. 그 잠깐의 흔적처럼, 오늘도 무언가를 남기고 싶다.",
    copyrightStatus: "original",
    level: 1,
    tags: ["겨울", "아침", "감성"],
  },
];
